default: &default
  adapter: postgresql
  encoding: utf8
  database: atprp1_dev
  username: rolph
  password: '*'


development:
  adapter: postgresql
  encoding: utf8
  database: atprp1_dev
  username: rolph
  password: '*'

production:
  adapter: postgresql
  encoding: utf8
  database: atprp1_production
  username: rolph
  password: '*'